version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
      - staticfiles:/static
    environment:
      - THREADS=4
    depends_on:
      - postgres
      
  postgres:
    image: "postgres:alpine"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    build: nginx/
    volumes:
      - staticfiles:/static
    ports:
      - "7070:8000"
    depends_on:
      - app


volumes:
  pgdata:
  elasticdata:
  staticfiles: