version: '3'
services:
  app:
    build: .
    command: "./manage.py runserver 0:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
    depends_on:
      - postgres
    ports:
      - "7070:8000"
      
  postgres:
    image: "postgres:alpine"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: