# Generated by Django 2.0.7 on 2018-07-19 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0022_auto_20180530_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketgroup',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='marketgroup',
            name='parent',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sde.MarketGroup'),
        ),
    ]
