# Generated by Django 2.0.7 on 2018-07-19 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0023_auto_20180719_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='market_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='sde.MarketGroup'),
        ),
    ]
