# Generated by Django 2.0.7 on 2018-07-19 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0024_auto_20180719_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('icon_file', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='marketgroup',
            name='icon_id',
        ),
        migrations.RemoveField(
            model_name='type',
            name='icon_id',
        ),
        migrations.AddField(
            model_name='marketgroup',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_groups', to='sde.Icon'),
        ),
        migrations.AddField(
            model_name='type',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types', to='sde.Icon'),
        ),
    ]
