# Generated by Django 2.0.7 on 2018-07-20 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0025_auto_20180719_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=128, null=True)),
                ('material_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkinLicense',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField(null=True)),
                ('skin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='sde.Skin')),
            ],
        ),
    ]
