# Generated by Django 2.0.7 on 2018-07-20 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0026_skin_skinlicense'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinlicense',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sde.Type'),
        ),
        migrations.AlterField(
            model_name='skinlicense',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
