# Generated by Django 2.0.7 on 2018-07-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0030_auto_20180720_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='material_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
