# Generated by Django 2.0.7 on 2018-07-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0032_auto_20180720_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=96)),
                ('display_name', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
    ]
