# Generated by Django 2.0.7 on 2018-07-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0033_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
