# Generated by Django 2.0.7 on 2018-07-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0034_auto_20180729_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='display_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
