# Generated by Django 2.0.7 on 2018-07-29 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0035_auto_20180729_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributetype',
            name='unit_id',
        ),
        migrations.AddField(
            model_name='attributetype',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sde.Unit'),
        ),
    ]
